app/src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $carrierName;

    /**
     * @ORM\Column(type="float")
     */
    private $carrierPrice;

    /**
     * @ORM\Column(type="text")
     */
    private $delivery;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetails::class, mappedBy="myOrder")
     */
    private $orderDetails;

    /**
     * @ORM\Column(type="boolean")
     */
    private $inProgress;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getTotal() {
        $total = null;
        foreach ($this->getOrderDetails()->getValues() as $product) {
            $total = $total + $product->getPrice();

        }
        //dd($total);
        return $total;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): self
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(float $carrierPrice): self
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection|OrderDetails[]
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetails $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetails $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    public function getInProgress(): ?bool
    {
        return $this->inProgress;
    }

    public function setInProgress(bool $inProgress): self
    {
        $this->inProgress = $inProgress;

        return $this;
    }
}

app/src/Entity/OrderDetails.php
<?php

namespace App\Entity;

use App\Repository\OrderDetailsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderDetailsRepository::class)
 */
class OrderDetails
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="orderDetails")
     * @ORM\JoinColumn(nullable=false)
     */
    private $myOrder;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_km;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expireAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_product;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $render_on;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMyOrder(): ?Order
    {
        return $this->myOrder;
    }

    public function setMyOrder(?Order $myOrder): self
    {
        $this->myOrder = $myOrder;

        return $this;
    }

    public function getProduct(): ?string
    {
        return $this->product;
    }

    public function setProduct(string $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getNbKm(): ?int
    {
        return $this->nb_km;
    }

    public function setNbKm(int $nb_km): self
    {
        $this->nb_km = $nb_km;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getExpireAt(): ?\DateTimeInterface
    {
        return $this->expireAt;
    }

    public function setExpireAt(\DateTimeInterface $expireAt): self
    {
        $this->expireAt = $expireAt;

        return $this;
    }

    public function getIdProduct(): ?int
    {
        return $this->id_product;
    }

    public function setIdProduct(int $id_product): self
    {
        $this->id_product = $id_product;

        return $this;
    }

    public function getRenderOn(): ?\DateTimeInterface
    {
        return $this->render_on;
    }

    public function setRenderOn(?\DateTimeInterface $render_on): self
    {
        $this->render_on = $render_on;

        return $this;
    }
}

app/src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Address;
use App\Entity\Carrier;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['user'];

        $builder
            ->add('addresses', EntityType::class, [
                'label' => false,
                'required' => true,
                'class' => Address::class,
                'choices' => $user->getAddresses(),
                'multiple' => false,
                'expanded' => true
            ])
            ->add('carriers', EntityType::class, [
                'label' => 'Choississez votre transporteur',
                'required' => true,
                'class' => Carrier::class,
                'multiple' => false,
                'expanded' => true
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Valider ma commande',
                'attr' => [
                    'class' => 'btn btn-success btn-block'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'user' => array()
        ]);
    }
}

app/src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\OrderDetails;
use App\Entity\Product;
use App\Classe\Cart;
use App\Form\OrderType;
use App\Entity\Order;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    private $entityManager;
    private $pdf;

    public function __construct(EntityManagerInterface $entityManager, Pdf $pdf)
    {
        $this->entityManager = $entityManager;
        $this->pdf = $pdf;
    }

    /**
     * @Route("/commande", name="order")
     */
    public function index(Cart $cart, Request $request): Response
    {
        if (!$this->getUser()->getAddresses()->getValues()) {
            return $this->redirectToRoute('account_address_add');
        }

        $form = $this->createForm(OrderType::class, null, [
            'user' => $this->getUser(),
        ]);

        return $this->render('order/index.html.twig', [
            'form' => $form->createView(),
            'cart' => $cart->getFull(),
        ]);
    }

    /**
     * @Route("/commande/recapitulatif", name="order_recap", methods = {"POST"})
     */
    public function add(Cart $cart, Request $request): Response
    {

        $form = $this->createForm(OrderType::class, null, [
            'user' => $this->getUser(),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $date = new \DateTime();
            $carriers = $form->get('carriers')->getData();
            $delivery = $form->get('addresses')->getData();
            $delivery_content = $delivery->getFirstName() . ' ' . $delivery->getLastName();
            $delivery_content .= '<br/>' . $delivery->getPhone();

            if ($delivery->getCompany()) {
                $delivery_content .= '<br/>' . $delivery->getCompany();
            }

            $delivery_content .= '<br/>' . $delivery->getAddress();
            $delivery_content .= '<br/>' . $delivery->getPostal() . ' ' . $delivery->getCity();
            $delivery_content .= '<br/>' . $delivery->getCountry();

            //dd($delivery_content);

            //Enregister ma commande
            $order = new Order();
            $order->setUser($this->getUser());
            $order->setCreatedAt($date);
            $order->setCarrierName($carriers->getName());
            $order->setCarrierPrice($carriers->getPrice());
            $order->setDelivery($delivery_content);
            $order->setInProgress(0);

            $this->entityManager->persist($order);

            //Enregister mes produits
            foreach ($cart->getFull()['products'] as $product) {
                //dd($product);
                $orderDetails = new OrderDetails();
                $orderDetails->setMyOrder($order);
                $orderDetails->setProduct($product['product']->getMarque());
                $orderDetails->setNbKm($product['nb_km']);
                $orderDetails->setDuree($product['duree']);
                $orderDetails->setPrice($product['price']);
                $orderDetails->setIdProduct($product['product']->getId());

                $interval = new \DateInterval('P' . $product['duree'] . 'D');
                $date = new \DateTime(null, new \DateTimeZone('Europe/Paris'));
                $expireAt = $date->add($interval);

                $orderDetails->setExpireAt($expireAt);

                $this->entityManager->persist($orderDetails);
            }
            $this->entityManager->flush();
            return $this->render('order/add.html.twig', [
                'cart' => $cart->getFull(),
                'carrier' => $carriers,
                'delivery' => $delivery_content
            ]);
        } else {
            return $this->redirectToRoute('cart');
        }
    }

    /**
     * @Route("/commande/success/", name="order_success")
     */

    //MAIL SI VEHICULES PAS RENDU DANS LES TEMPS
    //FACTURE QUAND VEHICULE RENDU
    //CONTRAT DE LOCATION QUAND VALIDE LA COMMANDE ENVOYE PAR MAIL


    public function success(Cart $cart): Response
    {

        $order = $this->entityManager->getRepository(Order::class)->findOneBy(
            ['user' => $this->getUser()->getId()],
            ['id' => 'DESC']
        );
        $order->setInProgress(1);

        $orders = $order->getOrderDetails()->getValues();
        //dd($orders);

        foreach ($orders as $order) {
            $product = $this->entityManager->getRepository(Product::class)->findOneById($order->getIdProduct());
            $product->setIsAvailable(0);
            //dd($product);
        }

        $this->entityManager->flush();

        $cart->remove();

        return $this->render('order/success.html.twig');

    }

    /**
     * @Route("/commande/contract/", name="order_contract")
     */

    public function createContractPdf()
    {

        $order = $this->entityManager->getRepository(Order::class)->findOneBy(
            ['user' => $this->getUser()->getId()],
            ['id' => 'DESC']
        );

        $products = $order->getOrderDetails()->getValues();
        $carrier = ['name' => $order->getCarrierName(), 'price' => $order->getCarrierPrice()];
//dd($products);
        $html = $this->renderView('order/contract.html.twig', array(
                'carrier' => $carrier,
                'delivery' => $order->getDelivery(),
                'products' => $products
            )
        );

        return new PdfResponse(
            $this->pdf->getOutputFromHtml($html, ['encoding' => 'UTF-8']),
            sprintf('contrat_de_location_%s.pdf', date('Y-m-d'))
        );

    }

    /**
     * @Route("/commande/contract/{id}", name="order_contract_one")
     */

    public function createOneContractPdf($id)
    {

        if($id) {

            $order = $this->entityManager->getRepository(Order::class)->findOneBy(
                [
                    'user' => $this->getUser()->getId(),
                    'id' => $id
                ],
            );

            //dd($order);

            $products = $order->getOrderDetails()->getValues();
            $carrier = ['name' => $order->getCarrierName(), 'price' => $order->getCarrierPrice()];

            //dd($products);

            $html = $this->renderView('order/contract.html.twig', array(
                    'carrier' => $carrier,
                    'delivery' => $order->getDelivery(),
                    'products' => $products
                )
            );

            return new PdfResponse(
                $this->pdf->getOutputFromHtml($html, ['encoding' => 'UTF-8']),
                sprintf('contrat_de_location_%s.pdf', date('Y-m-d'))
            );
        }
    }

    /**
     * @Route("/commande/historique/", name="order_history")
     */

    public function show()
    {

        $orders['inProgress'] = $this->entityManager->getRepository(Order::class)->findBy(
            [
                'user' => $this->getUser()->getId(),
                'inProgress' => 1
            ],
        );

        $orders['done'] = $this->entityManager->getRepository(Order::class)->findBy(
            [
                'user' => $this->getUser()->getId(),
                'inProgress' => 0
            ],
        );

        //dd($orders);

        return $this->render('order/show.html.twig', [
            'orders' => $orders
        ]);

    }


    /**
     * @Route("/commande/historique/{id}", name="order_history_details")
     */

    public function showOne($id)
    {

        $order = $this->entityManager->getRepository(Order::class)->findOneBy(
            [
                'user' => $this->getUser()->getId(),
                'inProgress' => 1,
                'id' => $id
            ]
        );
        if($order) {

            $orders = $order->getOrderDetails()->getValues();
            foreach ($orders as $order_product) {
                $products[] = $this->entityManager->getRepository(Product::class)->findOneById($order_product->getIdProduct());
            }

            //dd($orders);

            return $this->render('order/showOne.html.twig', [
                'products' => $products,
                'orders' => $orders
            ]);
        } else {
            return $this->redirectToRoute('order_history');
        }


    }

    /**
     * @Route("/commande/render/{idProduct}/{idOrderDetails}", name="order_render_product")
     */

    public function renderOne($idProduct, $idOrderDetails)
    {
        if($idProduct && $idOrderDetails) {

            $date = new \DateTime(null, new \DateTimeZone('Europe/Paris'));
            $order_detail = $this->entityManager->getRepository(OrderDetails::class)->findOneById($idOrderDetails);
            $order_detail->setRenderOn($date);

            $product = $this->entityManager->getRepository(Product::class)->findOneById($idProduct);
            $product->setIsAvailable(1);

            $id_order = $order_detail->getMyOrder()->getId();
            $order = $this->entityManager->getRepository(OrderDetails::class)->findBy([
                'myOrder' => $id_order
            ]);

            $endLocation = true;

           foreach ($order as $product) {
               if($product->getRenderOn() === null) {
                   $endLocation = false;
               }
           }

           if($endLocation) {
                $order = $this->entityManager->getRepository(Order::class)->findOneById($id_order);
                $order->setInProgress(0);
           }

           //dd($endLocation);

            $this->entityManager->flush();
            return $this->redirectToRoute('order_history_details', ['id' => $id_order]);

        }




    }
}

app/templates/order/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulatif de ma commande - eMove{% endblock %}

{% block content %}
    <h2>Mon récapitulatif</h2>
    <p>Vérifier vos informations avant de valider votre commande.</p>
    <hr>
    <div class="row">
        <div class="col-md-5">
            <strong>Mon adresse de livraison</strong> <br/>
            <div class="form-check mt-4">
                {{ delivery|raw }}
            </div>

            <hr>

            <div class="form-check">
                <strong>Mon transporteur</strong> <br/>
                {{ carrier.name }} <br/>
                {{ carrier.description }} <br/>
                {{ carrier.price|number_format(2, ',', '.') }} €
            </div>
        </div>
        <div class="col-md-5">
            <div class="text-center">
                <b>Ma commande</b><br/>
            </div>
            <div class="order-summary">
                {% set totalKm = null %}
                {% set totalDuree = null %}
                {% set totalPrice = null %}

                {% for product in cart.products %}
                    <div class="row mt-2">
                        <div class="col">
                            <img src="/uploads/{{ product.product.illustration }}" alt="{{ product.product.marque }}" height="75px">
                        </div>
                        <div class="col my-auto">
                            {{ product.product.marque }}
                            <small>{{ product.product.marque }}</small>
                        </div>
                        <div class="col my-auto">
                            {{ product.nb_km }} km | {{ product.duree }} jours
                        </div>
                    </div>

                    {% set totalKm = totalKm + product.nb_km %}
                    {% set totalDuree = totalDuree + product.duree %}
                    {% set totalPrice = totalPrice + product.price %}
                {% endfor %}


            </div>

            <hr>

            <strong>Nombre de véhicules : </strong> {{ cart|length }} <br/>
            <strong>Total de jours : </strong> {{ totalDuree }} <br/>
            <strong>Total de kilomètres : </strong> {{ totalKm }} <br/>
            <strong>Sous-Total : </strong> {{ totalPrice|number_format(2, ',', '.')  }} €<br/>
            <strong>Livraison : </strong> {{ carrier.price|number_format(2, ',', '.') }} €
            <br>
            <strong>Total : {{ (totalPrice + carrier.price)|number_format(2, ',', '.')  }}  €</strong>
            <a href="{{ path('order_success') }}" class="btn btn-success btn-block mt-3">Valider la commande | {{ (totalPrice + carrier.price)|number_format(2, ',', '.')  }}  €</a>
        </div>
    </div>
{% endblock %}

app/templates/order/contract.html.twig
{% block title %}Contrat de location - eMove{% endblock %}

{% block content %}
<h2>Mon contrat</h2>
<p>Voici le contrat de location, les voitures vous seront livré par le voiturier que vous avez choisi. Attention a rendre les véhicules dans les temps sinon il y aura des frais supplémentaires à hauteur de 200€ par heure de retard</p>
<hr>
<div class="row">
  <div class="col-md-5">
    <strong>Mon adresse de livraison</strong> <br/> <br/>
    <div class="form-check mt-4">
      {{ delivery|raw }}
    </div>

    <hr>

    <div class="form-check">
      <strong>Mon transporteur</strong> <br/> <br/>
      {{ carrier.name }} <br/>
      {{ carrier.price|number_format(2, ',', '.') }} €
    </div>
  </div> <br/>
  <div class="col-md-5">
    <div class="text-center">
      <b>Ma commande</b><br/>
    </div>
    <div class="order-summary">
      {% set totalKm = null %}
      {% set totalDuree = null %}
      {% set totalPrice = null %}

      {% for product in products %}
      <div class="row mt-2">
        <br/>
        <div class="col my-auto">
          {{ product.product }} | {{ product.nbKm }} km | {{ product.duree }} jours | {{ product.price }} € | à rendre avant le {{ product.expireAt|date('d/m/Y H:m:s') }}
        </div>

      </div>

      {% set totalKm = totalKm + product.nbKm %}
      {% set totalDuree = totalDuree + product.duree %}
      {% set totalPrice = totalPrice + product.price %}
      {% endfor %}


    </div>

    <hr>

    <strong>Nombre de véhicules : </strong> {{ products|length }} <br/>
    <strong>Total de jours : </strong> {{ totalDuree }} <br/>
    <strong>Total de kilomètres : </strong> {{ totalKm }} <br/>
    <strong>Sous-Total : </strong> {{ totalPrice|number_format(2, ',', '.')  }} €<br/>
    <strong>Livraison : </strong> {{ carrier.price|number_format(2, ',', '.') }} €
    <br>
    <strong>Total : {{ (totalPrice + carrier.price)|number_format(2, ',', '.')  }}  €</strong>
  </div>
</div>
{% endblock %}

app/templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Valider ma commande - eMove{% endblock %}

{% block content %}
    <h2>Je passe ma commande</h2>
    <p>Choisissez vos préférences avant de passer votre commande sur eMove.</p>
    <hr>
    <div class="row">
        <div class="col-md-4">
            {% set formHtml %}
                {{ form_start(form, {action:path('order_recap')}) }}
                    {{ form_label(form.addresses, 'Choissisez votre adresse de livraison') }}
                    <a href="{{ path('account_address_add') }}">Ajouter une nouvelle adresse</a>
                {{ form_end(form) }}
            {% endset %}

            {{ formHtml|replace({'[br]' : '<br/>'})|raw }}
        </div>
        <div class="col-md-4">
            <div class="text-center">
                <b>Récap de ma commande</b><br/>
                <p>Retrouvez le récapitulatif de vos produits.</p>
            </div>
            <div class="order-summary">
                {% for product in cart.products %}
                    <div class="row mt-2">
                        <div class="col">
                            <img src="/uploads/{{ product.product.illustration }}" alt="{{ product.product.marque }}" height="75px">
                        </div>
                        <div class="col my-auto">
                            {{ product.product.marque }}
                            <small>{{ product.product.marque }}</small>
                        </div>
                        <div class="col my-auto">
                            {{ product.nb_km }} km | {{ product.duree }} jours
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes - eMove{% endblock %}

{% block content %}
    {% if orders.inProgress|length > 0 %}
        <h3>Récapitulatif de vos locations en cours</h3>
        <table class="table">
                <thead>
                <tr>
                    <th scope="col">Commande passé le</th>
                    <th scope="col">Voiturier / Prix</th>
                    <th scope="col">Adresse de livraison</th>
                    <th scope="col">Prix (en €)</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% set totalKm = null %}
                {% set totalDuree = null %}
                {% set totalPrice = null %}

                {% for order in orders.inProgress %}
                    <tr>
                        <td>{{ order.createdAt|date('d/m/Y') }} à {{ order.createdAt|date('H:m:s') }}</td>
                        <td>{{ order.carrierName }} / <strong>{{ order.carrierPrice|number_format(2, ',', '.') }} €</strong></td>
                        <td>{{ order.delivery|raw }}</td>
                        <td>{{ order.getTotal|number_format(2, ',', '.') }} €</td>
                        <td>
                            <a href="{{ path('order_history_details', {'id': order.id}) }}" class="btn btn-sm btn-success">Rendre un véhicule</a>
                            <a href="{{ path('order_contract_one', {'id' : order.id}) }}" class="btn btn-sm btn-danger">Contrat de location</a>
                        </td>
                    </tr>



                {% endfor %}
                </tbody>
            </table>
    {% else %}
        <h3>Vous n'avez pas de location en cours</h3>
    {% endif %}
    <br/>
    {% if orders.done|length > 0 %}
        <h3>Récapitulatif de vos locations terminé</h3>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Commande passé le</th>
                <th scope="col">Voiturier / Prix</th>
                <th scope="col">Adresse de livraison</th>
                <th scope="col">Prix (en €)</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% set totalKm = null %}
            {% set totalDuree = null %}
            {% set totalPrice = null %}

            {% for order in orders.done %}
                <tr>
                    <td>{{ order.createdAt|date('d/m/Y') }} à {{ order.createdAt|date('H:m:s') }}</td>
                    <td>{{ order.carrierName }} / <strong>{{ order.carrierPrice|number_format(2, ',', '.') }} €</strong></td>
                    <td>{{ order.delivery|raw }}</td>
                    <td>{{ order.getTotal|number_format(2, ',', '.') }} €</td>
                    <td>
                        <a href="{{ path('order_contract_one', {'id' : order.id}) }}" class="btn btn-sm btn-danger">Facture</a>
                    </td>
                </tr>



            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3>Vous n'avez pas de location terminé</h3>
    {% endif %}
{% endblock %}

app/templates/order/showOne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes locations - eMove{% endblock %}

{% block content %}
    <h1>Historique de mes locations</h1>

    <p>Voici le détails de votre location</p>
    {% if products|length > 0 %}
        <table class="table">
            <thead>
            <tr>
                <th>Illustration</th>
                <th scope="col">Nom du produit</th>
                <th scope="col">Nombre de km</th>
                <th scope="col">Durée en jours</th>
                <th scope="col">Prix (en €)</th>
                <th scope="col">Rendre le véhicule avant le </th>
                <th scope="col">Status du véhicule</th>
                <th scope="col">Date de rendu du véhicule</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% set count = 0 %}

            {% for product in products %}
                <tr>

                    <th>
                        <img src="/uploads/{{ product.illustration }}" alt="{{ product.marque }}" height="75px">
                    </th>
                    <td>
                        {{ product.marque }}
                        <small>{{ product.marque }}</small>
                    </td>
                    <td>

                        {{ orders[count].nbKm }}

                    </td>
                    <td>
                        {{ orders[count].duree }}

                    </td>

                    <td>{{ orders[count].price }}</td>
                    <td>
                        {{ orders[count].expireAt|date('d/m/Y H:m:s') }}
                    </td>
                    <td>
                        {% if product.isAvailable %}
                            Disponible
                        {% else %}
                            En cours de location
                         {% endif %}
                    </td>
                    <td>
                        {% if orders[count].renderOn is null %}
                            Pas encore rendu
                        {% else %}
                            Rendu le {{ orders[count].renderOn|date('d/m/Y H:m:s') }}
                        {% endif %}
                    </td>
                    <td>
                        {% if orders[count].renderOn is null %}
                            <a href="{{ path('order_render_product', {'idProduct' : product.id, 'idOrderDetails' : orders[count].id }) }}" class="btn btn-sm btn-info">Rendre le véhicule ?</a>
                        {% endif %}
                    </td>
                </tr>
                {% set count = count + 1 %}
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

app/templates/order/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Validation de ma commande - eMove{% endblock %}

{% block content %}
    <h2>Validation de ma commande</h2>
    <p>Votre commande a été validé avec succès. Un contrat de location est disponible, il contient toute les modalités de votre location</p>
    <hr>
    <a href="{{ path('order_contract') }}" class="btn btn-sm btn-info">Télécharger votre contrat de location</a>

{% endblock %}